version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    restart: always
    ports:
      - "${APP_PORT:-5351}:80"
    volumes:
      - .:/var/www/html:z
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_NAME: ${DB_NAME:-decor_db}
      DB_USER: ${DB_USER:-postgres}
      DB_PASS: ${DB_PASS:-decor#12345}
      DB_PORT: ${DB_PORT:-5432}
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    # container_name dihapus agar tidak bentrok
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-decor_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-decor#12345}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: